### PR TITLE
fix: 581 environment lightformers are not working

### LINKED ISSUE #581: Environment Lightformers are not working
### Describe the bug

Adding a light former should create the object inside the envMap

```html
<Environment background preset="sunset" :blur="1" :frames="Infinity">
    <Lightformer
      :intensity="1"
      form="ring"
      color="red"
      :position="[-15, 4, -18]"
      :scale="10"
      :target="[0,0,0]"
    />
</Environment>
```

### Reproduction

https://stackblitz.com/~/edit/tresjs-environment-lightworkers?file=src/App.vue

### Steps to reproduce

_No response_

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/cientos: 4.0.3 => 4.0.3 
    @tresjs/core: 4.3.1 => 4.3.1 
    @tresjs/leches: ^0.14.0 => 0.14.0 
    vite: ^6.0.3 => 6.0.5
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by alvarosabu**
Closes #581 

@hawk86104 you were close with the slots watcher, it was one of the reasons, I just improved a couple of things. It should work now

https://github.com/user-attachments/assets/ab987223-9ec8-4de4-9394-812d8a4b4abc

### CODE REVIEW

File: src/core/staging/useEnvironment/component.vue [hunk 1]
```diff
@@ -24,37 +24,71 @@ const texture: Ref<Texture | CubeTexture | null> = ref(null)
...
   }
 }, -1)
-const useEnvironmentTexture = await useEnvironment(props, fbo)
+
+// Add environment map to virtual scene when available
+watch([useEnvironmentTexture, envSence], ([texture, scene]) => {
+  if (texture && scene?.virtualScene) {
+    // Clear previous environment
+    const rawScene = toRaw(scene).virtualScene
+    rawScene.children = rawScene.children.filter(
```
Comment (andretchen0) [inline src/core/staging/useEnvironment/component.vue:58]: It's probably best to avoid assigning to `children`. [THREE dispatches some events when `add/remove` is called](https://github.com/mrdoob/three.js/blob/79497a2c9b86036cfcc0c7ed448574f2d62de64d/src/core/Object3D.js#L377). And if anyone else happens to want to watch `children`, their references will no longer be valid after reassignment.

**Review by andretchen0 — CHANGES_REQUESTED** [review]
Works!

There's a memory leak to patch up or work around.

**Review by andretchen0 — APPROVED** [review]
