### PR TITLE
fix: 179 tweakpane plugin essentials

### LINKED ISSUE #179: Could not resolve "@tweakpane/plugin-essentials" since at least Cientos 3.1.0
### Describe the bug

I am doing: `vite`
I expect: vite to load without error, like it did for cientos < 3
What is actually happening: 
```
  VITE v4.4.9  ready in 1502 ms

  ➜  Local:   http://127.0.0.1:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Could not resolve "@tweakpane/plugin-essentials"

    node_modules/.pnpm/@tresjs+cientos@3.1.0_three@0.154.0_tweakpane@4.0.0_vue@3.3.4/node_modules/@tresjs/cientos/dist/trescientos.js:15:20:
      15 │ import * as xo from "@tweakpane/plugin-essentials";
         ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tweakpane/plugin-essentials" as external to exclude it from the bundle,
  which will remove this error.

 ELIFECYCLE  Command failed with exit code
```

### Reproduction

https://stackblitz.com/edit/tresjs-basic-hkgcpb?file=package.json

### Steps to reproduce

npm install && npm run dev

### System Info

_No response_

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by alvarosabu**
Closes #179

### CODE REVIEW

File: src/core/misc/useTweakPane/index.ts [hunk 1]
```diff
@@ -22,7 +22,7 @@ export /**
       pane.element.style.top = '1rem'
       pane.element.style.right = '1rem'
       pane.element.style.zIndex = '9999'
-      pane.registerPlugin(EssentialsPlugin)
+      /* pane.registerPlugin(EssentialsPlugin) */
```
Comment (JaimeTorrealba) [inline src/core/misc/useTweakPane/index.ts:25]: Why don't just delete it?

**Comment by JaimeTorrealba** [comment]
Additional, are you going to post some warning in the docs?

File: package.json [hunk 2]
```diff
@@ -46,27 +46,27 @@
...
-    "@types/node": "^20.4.5",
-    "@types/three": "^0.154.0",
-    "@typescript-eslint/eslint-plugin": "^6.2.0",
-    "@typescript-eslint/parser": "^6.2.0",
-    "@vitejs/plugin-vue": "^4.2.3",
-    "eslint": "^8.46.0",
-    "eslint-config-prettier": "^8.9.0",
-    "eslint-plugin-vue": "^9.15.1",
+    "@tweakpane/core": "^2.0.0",
+    "@tweakpane/plugin-essentials": "^0.2.0",
```
Comment (JaimeTorrealba) [inline package.json:56]: This should not be removed?

**Review by JaimeTorrealba — COMMENTED** [review]
Seems like there are some little conflict too
