### PR TITLE
fix: initial camera position in keyboard controls

### LINKED ISSUE #117: Pointerlock + Keyboard doesn't respect initial Camera position
### Describe the bug

Pointerlock + Keyboard is not respecting the initial camera position

Transition between initial camera position and `pointerlock` should be seamless

https://github.com/Tresjs/cientos/assets/4699008/f1c83c96-e20d-4d96-8181-9a79a5c8c094

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-wdhefd?description=Quick%20start%20repo%20for%20Tres.js%20projects&file=package.json,src%2Fcomponents%2FTheExperience.vue&title=TresJS

### Steps to reproduce

1. Click on canvas
2. See how the initial position of the Pointerlock differs from initial camera
3. Walk and jump
4. The camera goes under the grid (floor).

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/cientos: 2.2.0 => 2.2.0 
    @tresjs/core: 2.4.0 => 2.4.0 
    vite: ^4.3.9 => 4.3.9
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by JaimeTorrealba**
close #117

### CODE REVIEW

File: src/core/controls/KeyboardControls.vue [hunk 1]
```diff
@@ -105,6 +105,12 @@ const HBAmplitude = 0.3
 const initJumpTime = ref(0)
 const wrapperRef = shallowRef()
 const _forward = is2D ? 'y' : 'z'
+let initCameraPos = 0
+
+watch(state.container, () => {
```
Comment (alvarosabu) [inline src/core/controls/KeyboardControls.vue:110]: Wouldn't be better to watch the `state.camera` ? 

If your intention is to do it once the DOM is loaded, just use `onMounted` hook

**Review by alvarosabu — CHANGES_REQUESTED** [review]
