### PR TITLE
fix: 147 enhance environment and useenvironment abstractions

### LINKED ISSUE #147: Enhance Environment and useEnvironment abstractions
### Description

As a developer using TresJS, I want 
- Environment props to be reactive
- More presets other than 'sunset' (city, etc)

 so that:
- I can dynamically configure the preset or toggle the `background` property

### Suggested solution

Modify the `useEnvironment/component.ts` component so:

- Convert to vue file SFC
-  texture should be a ref
- Set the default for the props here.

Modify the `useEnvironment/index.ts` composable so:

- Reacts to prop changes (Using watchers and computed)
- Return the texture as a ref

 

### Alternative

_No response_

### Additional context

_No response_

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by alvarosabu**
Closes #147

### CODE REVIEW

File: docs/.vitepress/theme/components/EnvironmentDemo.vue [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+    step: 0.01,
+  },
+}, {
+  uuid: 'environment',
+})
+
+const environmentRef = ref(null)
+
+watchEffect(() => {
+  console.log(background.value.value)
```
Comment (JaimeTorrealba) [inline docs/.vitepress/theme/components/EnvironmentDemo.vue:36]: Let's remove the console in the docs,

**Review by JaimeTorrealba — CHANGES_REQUESTED** [review]
I like the component, just remove a bunch of unnecessary stuff, and merge with main :)

Thanks for this man
